ARG NSO_VERSION=latest
ARG PKG_VERSION=0.0.0
ARG REGISTRY=registry

FROM ${REGISTRY}cisco-nso-build:${NSO_VERSION} AS build
{% if unmanaged %}
COPY --chown=nso ./src /nso/run/packages/{{ name }}
{% else %}
COPY --chown=nso ./src/src /nso/run/packages/{{ name }}/src
{% if dependencies %}
{% for dep in dependencies %}
COPY --from=deps {{ dep }}.tar.gz /tmp/
RUN tar -xzf /tmp/{{ dep }}.tar.gz -C /nso/run/packages && \
    chown -R nso /nso/run/packages/{{ dep }}
{% endfor %}
{% endif %}
{% endif %}
RUN make -C /nso/run/packages/{{ name }}/src clean all
{% if py_requirements %}
WORKDIR /nso/run/packages/{{ name }}
RUN pip install --target ./python -r src/requirements.txt
{% endif %}

{% if unmanaged %}
FROM scratch
COPY --from=build /nso/run/packages/{{ name }} /{{ name }}
{% else %}
FROM ${REGISTRY}cisco-nso-build:${NSO_VERSION} AS update
COPY --chown=nso ./src /{{ name }}

FROM ${REGISTRY}cisco-nso-build:${NSO_VERSION} AS version
ARG PKG_VERSION
COPY --from=update /{{ name }}/package-meta-data.xml /tmp/package-meta-data.xml
RUN sed -i -E "s|(<package-version>)[^<]*(</package-version>)|\1${PKG_VERSION}\2|" /tmp/package-meta-data.xml

FROM scratch
COPY --from=build /nso/run/packages/{{ name }} /{{ name }}
COPY --from=update /{{ name }} /{{ name }}
COPY --from=version /tmp/package-meta-data.xml /{{ name }}/package-meta-data.xml
{% endif %}
